import {
  Client,
  ServiceCatalogItem,
  ClientService,
  Payment,
  Project,
  Task,
  ActivityLog,
  AppSettings,
  FullDatabase,
  Expense,
  Invoice,
  ChecklistTemplate,
  ClientChecklist,
  ClientPerformanceEntry,
  ClientWebsite,
} from '../types';

export const DEFAULT_CATALOG: ServiceCatalogItem[] = [
  // Website Build
  {
    id: 'cat_web_landing',
    name: 'Website Build: Landing Page',
    category: 'Website Build',
    billingType: 'one-time',
    defaultPrice: 1200,
    setupFee: 0,
    minimumTermMonths: 0,
    active: true,
  },
  {
    id: 'cat_web_add_page',
    name: 'Website Build: Additional Page',
    category: 'Website Build',
    billingType: 'one-time',
    defaultPrice: 500,
    setupFee: 0,
    minimumTermMonths: 0,
    active: true,
  },
  // Website Care Plan (12-month minimum)
  {
    id: 'cat_care_essential',
    name: 'Website Care Plan: Essential',
    category: 'Website Care Plan',
    billingType: 'monthly',
    defaultPrice: 97,
    setupFee: 0,
    minimumTermMonths: 12,
    active: true,
  },
  {
    id: 'cat_care_growth',
    name: 'Website Care Plan: Growth',
    category: 'Website Care Plan',
    billingType: 'monthly',
    defaultPrice: 297,
    setupFee: 0,
    minimumTermMonths: 12,
    active: true,
  },
  {
    id: 'cat_care_partner',
    name: 'Website Care Plan: Partner',
    category: 'Website Care Plan',
    billingType: 'monthly',
    defaultPrice: 697,
    setupFee: 0,
    minimumTermMonths: 12,
    active: true,
  },
  // Google Business Profile (3-month minimum)
  {
    id: 'cat_gbp_buildout',
    name: 'Google Business Profile: Buildout',
    category: 'Google Business Profile',
    billingType: 'one-time',
    defaultPrice: 500,
    setupFee: 0,
    minimumTermMonths: 0,
    active: true,
  },
  {
    id: 'cat_gbp_maintain',
    name: 'Google Business Profile: Maintain',
    category: 'Google Business Profile',
    billingType: 'monthly',
    defaultPrice: 250,
    setupFee: 0,
    minimumTermMonths: 3,
    active: true,
  },
  {
    id: 'cat_gbp_grow',
    name: 'Google Business Profile: Grow',
    category: 'Google Business Profile',
    billingType: 'monthly',
    defaultPrice: 450,
    setupFee: 0,
    minimumTermMonths: 3,
    active: true,
  },
  {
    id: 'cat_gbp_dominate',
    name: 'Google Business Profile: Dominate Local',
    category: 'Google Business Profile',
    billingType: 'monthly',
    defaultPrice: 750,
    setupFee: 0,
    minimumTermMonths: 3,
    active: true,
  },
  // Ads Management (3-month minimum; client pays ad spend directly)
  {
    id: 'cat_ads_starter',
    name: 'Ads Management: Starter',
    category: 'Ads Management',
    billingType: 'monthly',
    defaultPrice: 600,
    setupFee: 400,
    minimumTermMonths: 3,
    active: true,
  },
  {
    id: 'cat_ads_growth',
    name: 'Ads Management: Growth',
    category: 'Ads Management',
    billingType: 'monthly',
    defaultPrice: 1000,
    setupFee: 1200,
    minimumTermMonths: 3,
    active: true,
  },
  {
    id: 'cat_ads_dominate',
    name: 'Ads Management: Dominate',
    category: 'Ads Management',
    billingType: 'monthly',
    defaultPrice: 1800,
    setupFee: 1800,
    minimumTermMonths: 3,
    active: true,
  },
  // Add-ons & Creatives
  {
    id: 'cat_addon_video',
    name: 'Motion / Video Ad',
    category: 'Creative Add-on',
    billingType: 'one-time',
    defaultPrice: 250,
    setupFee: 0,
    minimumTermMonths: 0,
    active: true,
  },
  {
    id: 'cat_addon_creative',
    name: 'Extra Creative Asset',
    category: 'Creative Add-on',
    billingType: 'one-time',
    defaultPrice: 75,
    setupFee: 0,
    minimumTermMonths: 0,
    active: true,
  },
  {
    id: 'cat_addon_spanish',
    name: 'Spanish Ad Set Expansion',
    category: 'Creative Add-on',
    billingType: 'monthly',
    defaultPrice: 150,
    setupFee: 0,
    minimumTermMonths: 3,
    active: true,
  },
  {
    id: 'cat_addon_landing',
    name: 'Additional Campaign Landing Page',
    category: 'Website Build',
    billingType: 'one-time',
    defaultPrice: 500,
    setupFee: 0,
    minimumTermMonths: 0,
    active: true,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  agencyName: 'Dynasty Digital',
  phone: '(954) 294-3230',
  email: 'info@dynastysites.net',
  website: 'https://dynastysites.net',
  location: 'Fort Lauderdale, South Florida',
  defaultBillingDay: 1,
  pinEnabled: true,
  pinCode: '1234',
  leadsSecretKey: 'dd_secret_leads_2026_cr',
};

export const SAMPLE_CLIENTS: Client[] = [
  {
    id: 'cli_palm_shore',
    businessName: 'Palm & Shore Landscaping',
    contactName: 'Mateo Morales',
    email: 'mateo@palmandshorefl.com',
    phone: '(561) 849-2210',
    website: 'https://palmandshorefl.com',
    address: '1420 N Federal Hwy',
    city: 'Boca Raton, FL',
    industry: 'Landscaping',
    leadSource: 'Google Ads',
    status: 'Active Client',
    tags: ['High Value', 'Commercial', 'Year-Round'],
    dateAdded: '2026-02-10',
    notes: 'Premium commercial and residential landscaping across Boca Raton and Delray. Loves weekly ad reports.',
    accessInfo: 'Domain on Cloudflare (shared delegation to Dynasty Digital); Meta Business Portfolio ID 9102488102; Google Search Console connected.',
    lastActivityDate: '2026-10-04T14:30:00Z',
    documents: {
      proposal: {
        link: 'https://dynastysites.net/proposals/palm-shore-growth-2026.pdf',
        sentDate: '2026-02-05',
        acceptedDate: '2026-02-08',
      },
      agreement: {
        link: 'https://dynastysites.net/agreements/palm-shore-msa-signed.pdf',
        signedDate: '2026-02-10',
        eSignStatus: 'Signed',
      },
      paymentTermsVersion: 'DD-Standard Net 15 v2026.1',
      paymentTermsSummary: 'Net 15 - Auto ACH billing via Stripe on the 1st of every month.',
      fileLinks: [
        {
          id: 'fl_ps_1',
          title: 'Brand Vector Logos & Style Guide',
          url: 'https://drive.google.com/drive/folders/palm-shore-assets',
          category: 'Brand Assets',
          addedDate: '2026-02-11',
        },
        {
          id: 'fl_ps_2',
          title: 'Google Ads & Cloudflare Credential Vault',
          url: 'https://bitwarden.com/vault/shared/palm-creds',
          category: 'Access & Logins',
          addedDate: '2026-02-15',
        },
      ],
    },
  },
  {
    id: 'cli_sparkle_pro',
    businessName: 'Sparkle Pro Cleaning',
    contactName: 'Luciana Silva',
    email: 'luciana@sparkleproclean.com',
    phone: '(954) 732-8841',
    website: 'https://sparkleproclean.com',
    address: '3200 E Commercial Blvd',
    city: 'Fort Lauderdale, FL',
    industry: 'Cleaning',
    leadSource: 'Meta Ads',
    status: 'Active Client',
    tags: ['Residential', 'Airbnb Turnover', 'Overdue Follow-up'],
    dateAdded: '2026-04-15',
    notes: 'Vacation rental & residential turnover. Needs payment reminder for October retainer.',
    accessInfo: 'GoDaddy domain (delegated access to info@dynastysites.net); GBP manager invite accepted 04/16; Stripe billing handled on client side.',
    lastActivityDate: '2026-10-01T09:15:00Z',
    documents: {
      proposal: {
        link: 'https://dynastysites.net/proposals/sparkle-pro-retainer.pdf',
        sentDate: '2026-04-10',
        acceptedDate: '2026-04-12',
      },
      agreement: {
        link: 'https://dynastysites.net/agreements/sparkle-pro-msa-pending.pdf',
        eSignStatus: 'Sent for Signature',
      },
      paymentTermsVersion: 'DD-Standard Net 15 v2026.1',
      paymentTermsSummary: 'Card payment processed on invoice issue date.',
      fileLinks: [
        {
          id: 'fl_sp_1',
          title: 'Cleaning Rates & Residential Scope PDF',
          url: 'https://drive.google.com/file/d/sparkle-scope.pdf',
          category: 'Creative',
          addedDate: '2026-04-16',
        },
      ],
    },
  },
  {
    id: 'cli_gold_coast',
    businessName: 'Gold Coast Mobile Detailing',
    contactName: 'Derek Vaughn',
    email: 'derek@goldcoastautofl.com',
    phone: '(561) 670-3490',
    website: 'https://goldcoastautofl.com',
    address: '780 SE 5th Ave',
    city: 'Delray Beach, FL',
    industry: 'Auto Detailing',
    leadSource: 'Referral',
    status: 'Active Client',
    tags: ['Ceramic Coating', 'Renewal Soon', 'Loyal'],
    dateAdded: '2025-10-25',
    notes: 'High-end mobile detailing van fleet. Contract initial term ends in late October. Great candidate for 12-mo extension with video creative add-on.',
    accessInfo: 'Namecheap domain pointed to Dynasty Vercel host; Google Ads manager account linked (MCC); Google Business Profile owned by Derek.',
    lastActivityDate: '2026-10-06T11:00:00Z',
    documents: {
      proposal: {
        link: 'https://dynastysites.net/proposals/gold-coast-revamp-2025.pdf',
        sentDate: '2025-10-18',
        acceptedDate: '2025-10-22',
      },
      agreement: {
        link: 'https://dynastysites.net/agreements/gold-coast-annual-signed.pdf',
        signedDate: '2025-10-25',
        eSignStatus: 'Signed',
      },
      paymentTermsVersion: 'DD-12Mo Retainer v2025.3',
      paymentTermsSummary: 'Prepaid retainer monthly on the 1st; 2.9% credit card processing terms.',
      fileLinks: [
        {
          id: 'fl_gc_1',
          title: 'High-Res Vehicle Photo Archive',
          url: 'https://dropbox.com/sh/goldcoast-photos',
          category: 'Creative',
          addedDate: '2025-11-01',
        },
      ],
    },
  },
  {
    id: 'cli_sunshine_hvac',
    businessName: 'Sunshine Coast HVAC & Air',
    contactName: 'Frankie Gallo',
    email: 'frankie@sunshinecoasthvac.com',
    phone: '(954) 551-7729',
    website: 'https://sunshinecoasthvac.com',
    address: '2100 Atlantic Blvd',
    city: 'Pompano Beach, FL',
    industry: 'HVAC',
    leadSource: 'Google Business',
    status: 'Proposal Sent',
    tags: ['AC Replacement', 'Commercial Quote', 'Hot Lead'],
    dateAdded: '2026-09-28',
    notes: 'Sent formal proposal for 5-page conversion site + GBP Dominate package. Waiting for sign-off this Friday.',
    accessInfo: 'Current Wix site login shared during discovery call; wants domain moved to custom Next.js landing stack.',
    lastActivityDate: '2026-10-05T16:20:00Z',
    documents: {
      proposal: {
        link: 'https://dynastysites.net/proposals/sunshine-coast-hvac-q4-2026.pdf',
        sentDate: '2026-09-30',
      },
      agreement: {
        eSignStatus: 'Not Sent',
      },
      paymentTermsVersion: 'DD-Standard 50/50 Deposit v2026.1',
      paymentTermsSummary: '50% deposit before design kickoff, 50% upon final sign-off prior to launch.',
      fileLinks: [],
    },
  },
  {
    id: 'cli_atlantic_remodel',
    businessName: 'Atlantic Remodeling Pros',
    contactName: 'Carlos Mendonca',
    email: 'carlos@atlanticremodelfl.com',
    phone: '(954) 412-9980',
    website: '',
    address: '8850 University Dr',
    city: 'Coral Springs, FL',
    industry: 'Remodeling/Contractor',
    leadSource: 'Meta Ads',
    status: 'Lead',
    tags: ['Meta Lead Ads', 'Kitchen & Bath', 'Inbound'],
    dateAdded: '2026-10-07',
    notes: 'Inbound lead via Meta Lead Ads form. Interested in full website redesign and local Google ads for kitchen & bath remodeling in Broward County.',
    accessInfo: 'No domain or assets created yet. Dynasty Digital to advise on brand registration.',
    lastActivityDate: '2026-10-07T09:55:00Z',
    leadContacted: false,
    sourceMessage: 'Looking for a new website and lead generation campaign for high-end kitchen remodels. Ready to start this month.',
    documents: {
      agreement: {
        eSignStatus: 'Not Sent',
      },
      fileLinks: [],
    },
  },
  {
    id: 'cli_boutique_wellness',
    businessName: 'Boutique Wellness Haven',
    contactName: 'Elena Rostova',
    email: 'elena@wellnesshavenmia.com',
    phone: '(305) 912-3844',
    website: 'https://wellnesshavenmia.com',
    address: '19501 Biscayne Blvd, Suite 410',
    city: 'Aventura, FL',
    industry: 'Wellness',
    leadSource: 'Website Form',
    status: 'Active Client',
    tags: ['Med Spa', 'Custom Build', 'High Ticket'],
    dateAdded: '2026-08-14',
    notes: 'Luxury med spa & cryotherapy clinic. Custom booking site in build stage; monthly Care Plan Partner starting upon launch.',
    accessInfo: 'Squarespace domain to be repointed; JaneApp booking widget iframe embeds; Meta Ads Partner ID approved.',
    lastActivityDate: '2026-10-06T15:45:00Z',
    documents: {
      proposal: {
        link: 'https://dynastysites.net/proposals/boutique-wellness-proposal.pdf',
        sentDate: '2026-08-10',
        acceptedDate: '2026-08-12',
      },
      agreement: {
        link: 'https://dynastysites.net/agreements/boutique-wellness-agreement-draft.pdf',
        eSignStatus: 'Draft',
      },
      paymentTermsVersion: 'DD-Standard 50/50 Deposit v2026.1',
      paymentTermsSummary: '50% project deposit billed; Care Plan Partner billed monthly on the 1st upon launch.',
      fileLinks: [
        {
          id: 'fl_bw_1',
          title: 'Spa Floorplan & Room High-Res Photography',
          url: 'https://drive.google.com/drive/folders/boutique-wellness-photos',
          category: 'Creative',
          addedDate: '2026-08-20',
        },
      ],
    },
  },
];

export const SAMPLE_SERVICES: ClientService[] = [
  // 1. Palm & Shore Landscaping (Active, Paid, Solid)
  {
    id: 'srv_palm_care',
    clientId: 'cli_palm_shore',
    catalogItemId: 'cat_care_growth',
    customName: 'Website Care Plan: Growth',
    category: 'Website Care Plan',
    billingType: 'monthly',
    price: 297,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-02-15',
    minimumTermMonths: 12,
    endDate: '2027-02-15',
    autoRenew: true,
    status: 'Active',
    billingDayOfMonth: 15,
    notes: 'Bi-weekly content updates, daily backups, Speed boost.',
  },
  {
    id: 'srv_palm_ads',
    clientId: 'cli_palm_shore',
    catalogItemId: 'cat_ads_growth',
    customName: 'Ads Management: Growth (Google & Meta)',
    category: 'Ads Management',
    billingType: 'monthly',
    price: 1000,
    setupFee: 1200,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-03-01',
    minimumTermMonths: 6,
    endDate: '2026-09-01',
    autoRenew: true,
    status: 'Active',
    billingDayOfMonth: 1,
    adSpendBudget: 2500,
    notes: '$2,500/mo ad spend paid directly to Google/Meta by Mateo.',
  },
  {
    id: 'srv_palm_gbp',
    clientId: 'cli_palm_shore',
    catalogItemId: 'cat_gbp_maintain',
    customName: 'Google Business Profile: Maintain',
    category: 'Google Business Profile',
    billingType: 'monthly',
    price: 250,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-03-01',
    minimumTermMonths: 6,
    endDate: '2026-09-01',
    autoRenew: true,
    status: 'Active',
    billingDayOfMonth: 1,
    notes: '2 Google posts per week, monthly geotagged photo updates.',
  },

  // 2. Sparkle Pro Cleaning (OVERDUE! Billing day 1st, no payment logged in October)
  {
    id: 'srv_sparkle_care',
    clientId: 'cli_sparkle_pro',
    catalogItemId: 'cat_care_essential',
    customName: 'Website Care Plan: Essential',
    category: 'Website Care Plan',
    billingType: 'monthly',
    price: 97,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-04-20',
    minimumTermMonths: 12,
    endDate: '2027-04-20',
    autoRenew: true,
    status: 'Active',
    billingDayOfMonth: 1,
    notes: 'Monthly security audits, plugin maintenance.',
  },
  {
    id: 'srv_sparkle_gbp',
    clientId: 'cli_sparkle_pro',
    catalogItemId: 'cat_gbp_dominate',
    customName: 'Google Business Profile: Dominate Local',
    category: 'Google Business Profile',
    billingType: 'monthly',
    price: 750,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-05-01',
    minimumTermMonths: 6,
    endDate: '2026-11-01',
    autoRenew: true,
    status: 'Active',
    billingDayOfMonth: 1,
    notes: 'Local citation building, review response automation, weekly promotion posts.',
  },

  // 3. Gold Coast Mobile Detailing (RENEWAL WINDOW - ends in 18 days on Oct 25, 2026!)
  {
    id: 'srv_gold_care',
    clientId: 'cli_gold_coast',
    catalogItemId: 'cat_care_growth',
    customName: 'Website Care Plan: Growth',
    category: 'Website Care Plan',
    billingType: 'monthly',
    price: 297,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2025-10-25',
    minimumTermMonths: 12,
    endDate: '2026-10-25',
    autoRenew: false,
    status: 'Active',
    billingDayOfMonth: 25,
    notes: '12-month initial term reaching maturity. Ready for extension.',
  },
  {
    id: 'srv_gold_ads',
    clientId: 'cli_gold_coast',
    catalogItemId: 'cat_ads_starter',
    customName: 'Ads Management: Starter (Meta Local)',
    category: 'Ads Management',
    billingType: 'monthly',
    price: 600,
    setupFee: 400,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-07-25',
    minimumTermMonths: 3,
    endDate: '2026-10-25',
    autoRenew: false,
    status: 'Active',
    billingDayOfMonth: 25,
    adSpendBudget: 1200,
    notes: '3-month intro test expiring Oct 25. High booking return.',
  },

  // 4. Boutique Wellness Haven (Build Project in Progress + Upcoming Retainer)
  {
    id: 'srv_wellness_build',
    clientId: 'cli_boutique_wellness',
    catalogItemId: 'cat_web_landing',
    customName: 'Website Build: Custom Med Spa Portal (5 Pages)',
    category: 'Website Build',
    billingType: 'one-time',
    price: 3200,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-09-01',
    minimumTermMonths: 0,
    endDate: '2026-10-31',
    autoRenew: false,
    status: 'Active',
    billingDayOfMonth: 1,
    notes: '$1,600 deposit paid, $1,600 due on launch.',
  },
  {
    id: 'srv_wellness_partner',
    clientId: 'cli_boutique_wellness',
    catalogItemId: 'cat_care_partner',
    customName: 'Website Care Plan: Partner Tier',
    category: 'Website Care Plan',
    billingType: 'monthly',
    price: 697,
    setupFee: 0,
    discountType: 'fixed',
    discountValue: 0,
    startDate: '2026-11-01',
    minimumTermMonths: 12,
    endDate: '2027-11-01',
    autoRenew: true,
    status: 'Pending',
    billingDayOfMonth: 1,
    notes: 'Scheduled to activate right upon official site launch.',
  },
];

export const SAMPLE_PAYMENTS: Payment[] = [
  // Palm & Shore (Recent Oct 1 payments)
  {
    id: 'pay_palm_oct_ads',
    clientId: 'cli_palm_shore',
    clientServiceId: 'srv_palm_ads',
    amount: 1000,
    date: '2026-10-01',
    method: 'ACH',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-088',
    notes: 'October Google/Meta ads retainer.',
  },
  {
    id: 'pay_palm_oct_gbp',
    clientId: 'cli_palm_shore',
    clientServiceId: 'srv_palm_gbp',
    amount: 250,
    date: '2026-10-01',
    method: 'ACH',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-089',
    notes: 'October GBP management.',
  },
  {
    id: 'pay_palm_sep_care',
    clientId: 'cli_palm_shore',
    clientServiceId: 'srv_palm_care',
    amount: 297,
    date: '2026-09-15',
    method: 'Card/Stripe',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-074',
    notes: 'September Care Plan Growth.',
  },

  // Sparkle Pro Cleaning (Paid in September, but October 1 is missing -> Overdue!)
  {
    id: 'pay_sparkle_sep_care',
    clientId: 'cli_sparkle_pro',
    clientServiceId: 'srv_sparkle_care',
    amount: 97,
    date: '2026-09-01',
    method: 'Card/Stripe',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-068',
    notes: 'September Care Plan.',
  },
  {
    id: 'pay_sparkle_sep_gbp',
    clientId: 'cli_sparkle_pro',
    clientServiceId: 'srv_sparkle_gbp',
    amount: 750,
    date: '2026-09-01',
    method: 'Card/Stripe',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-069',
    notes: 'September GBP Dominate.',
  },

  // Gold Coast Mobile Detailing (Paid in September)
  {
    id: 'pay_gold_sep_care',
    clientId: 'cli_gold_coast',
    clientServiceId: 'srv_gold_care',
    amount: 297,
    date: '2026-09-25',
    method: 'Zelle',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-081',
    notes: 'September Retainer via Zelle.',
  },
  {
    id: 'pay_gold_sep_ads',
    clientId: 'cli_gold_coast',
    clientServiceId: 'srv_gold_ads',
    amount: 600,
    date: '2026-09-25',
    method: 'Zelle',
    type: 'Monthly',
    status: 'Paid',
    invoiceNumber: 'INV-2026-082',
    notes: 'September Meta Ads retainer.',
  },

  // Boutique Wellness Haven (Deposit Paid)
  {
    id: 'pay_wellness_deposit',
    clientId: 'cli_boutique_wellness',
    clientServiceId: 'srv_wellness_build',
    amount: 1600,
    date: '2026-09-02',
    method: 'Card/Stripe',
    type: 'Deposit',
    status: 'Paid',
    invoiceNumber: 'INV-2026-070',
    notes: '50% project deposit for custom portal build.',
  },
];

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj_wellness_build',
    clientId: 'cli_boutique_wellness',
    name: 'Luxury Med Spa Portal & Booking System',
    stage: 'Build',
    mockupDue: '2026-09-15',
    targetLaunch: '2026-10-20',
    depositPaid: true,
    finalPaid: false,
    previewLink: 'https://preview-wellness.dynastysites.net',
    liveLink: 'https://wellnesshavenmia.com',
    notes: 'Hero section and booking embed approved. Currently implementing mobile speed optimizations and Spanish treatment pages.',
    updatedAt: '2026-10-06T15:00:00Z',
  },
  {
    id: 'proj_sunshine_mockup',
    clientId: 'cli_sunshine_hvac',
    name: 'High-Conversion AC Replacement Funnel',
    stage: 'Proposal',
    mockupDue: '2026-10-02',
    targetLaunch: '2026-10-30',
    depositPaid: false,
    finalPaid: false,
    previewLink: 'https://figma.com/@dynastydigital/sunshine-hvac-mockup',
    notes: 'Figma interactive prototype shared with Frankie during proposal presentation.',
    updatedAt: '2026-10-05T12:00:00Z',
  },
];

export const SAMPLE_TASKS: Task[] = [
  {
    id: 'tsk_followup_atlantic_5m',
    clientId: 'cli_atlantic_remodel',
    title: '⚡ Follow up within 5 minutes — Carlos Mendonca (Atlantic Remodeling Pros)',
    dueDate: '2026-10-07',
    priority: 'High',
    done: false,
    type: 'Follow-up',
    createdAt: '2026-10-07T09:55:00Z',
    autoGenerated: true,
  },
  {
    id: 'tsk_sparkle_remind',
    clientId: 'cli_sparkle_pro',
    title: 'Send friendly WhatsApp / SMS reminder for October Retainer ($847)',
    dueDate: '2026-10-07',
    priority: 'High',
    done: false,
    type: 'Renewal',
    createdAt: '2026-10-06T08:00:00Z',
  },
  {
    id: 'tsk_gold_renewal',
    clientId: 'cli_gold_coast',
    title: 'Schedule Q4 contract renewal & video ads upsell call with Derek',
    dueDate: '2026-10-10',
    priority: 'High',
    done: false,
    type: 'Renewal',
    createdAt: '2026-10-05T10:00:00Z',
  },
  {
    id: 'tsk_wellness_build_finish',
    clientId: 'cli_boutique_wellness',
    title: 'Hook up JaneApp iframe embed & verify mobile SSL before final review',
    dueDate: '2026-10-12',
    priority: 'Medium',
    done: false,
    type: 'Build',
    createdAt: '2026-10-04T11:00:00Z',
  },
  {
    id: 'tsk_atlantic_followup',
    clientId: 'cli_atlantic_remodel',
    title: 'Follow up with Carlos: send 2 portfolio links for contractor websites',
    dueDate: '2026-10-07',
    priority: 'Medium',
    done: false,
    type: 'Follow-up',
    createdAt: '2026-10-02T10:00:00Z',
    autoGenerated: true,
  },
  {
    id: 'tsk_palm_monthly_rep',
    clientId: 'cli_palm_shore',
    title: 'Send September Google Ads & GBP Performance Report to Mateo',
    dueDate: '2026-10-03',
    priority: 'Low',
    done: true,
    type: 'Report',
    createdAt: '2026-10-01T08:00:00Z',
    autoGenerated: true,
  },
  {
    id: 'tsk_care_palm_2026_10',
    clientId: 'cli_palm_shore',
    title: 'Care plan maintenance — Palm & Shore Landscaping',
    dueDate: '2026-10-15',
    priority: 'Medium',
    done: false,
    type: 'Monthly Care',
    createdAt: '2026-10-01T09:00:00Z',
    autoGenerated: true,
  },
  {
    id: 'tsk_care_sparkle_2026_10',
    clientId: 'cli_sparkle_pro',
    title: 'Care plan maintenance — Sparkle Pro Cleaning',
    dueDate: '2026-10-15',
    priority: 'Medium',
    done: false,
    type: 'Monthly Care',
    createdAt: '2026-10-01T09:00:00Z',
    autoGenerated: true,
  },
  {
    id: 'tsk_care_gold_2026_10',
    clientId: 'cli_gold_coast',
    title: 'Care plan maintenance — Gold Coast Mobile Detailing',
    dueDate: '2026-10-15',
    priority: 'Medium',
    done: false,
    type: 'Monthly Care',
    createdAt: '2026-10-01T09:00:00Z',
    autoGenerated: true,
  },
  {
    id: 'tsk_care_wellness_2026_10',
    clientId: 'cli_boutique_wellness',
    title: 'Care plan maintenance — Coastal Glow Wellness',
    dueDate: '2026-10-15',
    priority: 'Medium',
    done: false,
    type: 'Monthly Care',
    createdAt: '2026-10-01T09:00:00Z',
    autoGenerated: true,
  },
];

export const SAMPLE_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act_1',
    clientId: 'cli_palm_shore',
    type: 'payment_logged',
    title: 'Payment Received: $1,250.00',
    description: 'Received $1,000 for Ads Retainer and $250 for GBP Maintain via ACH transfer.',
    timestamp: '2026-10-01T15:20:00Z',
  },
  {
    id: 'act_2',
    clientId: 'cli_sparkle_pro',
    type: 'note',
    title: 'Billing Alert Flagged',
    description: 'October retainer overdue by 6 days. Luciana mentioned changing business debit card.',
    timestamp: '2026-10-06T09:30:00Z',
  },
  {
    id: 'act_3',
    clientId: 'cli_gold_coast',
    type: 'meeting',
    title: 'Quarterly Check-in Call with Derek',
    description: 'Reviewed ceramic coating campaign results: 38 new inbound bookings in September. Mentioned wanting Instagram video ads for holiday promo.',
    timestamp: '2026-10-06T11:00:00Z',
  },
  {
    id: 'act_4',
    clientId: 'cli_sunshine_hvac',
    type: 'status_change',
    title: 'Status Updated to Proposal Sent',
    description: 'Presented proposal for $1,200 landing page build + $750/mo GBP Dominate local package.',
    timestamp: '2026-10-05T16:20:00Z',
  },
  {
    id: 'act_5',
    clientId: 'cli_atlantic_remodel',
    type: 'call',
    title: 'Discovery Phone Call (15 min)',
    description: 'Connected with Carlos. He is booked 3 months out with kitchen jobs, but has zero website or Google presence. Wants to build authority brand.',
    timestamp: '2026-10-02T10:00:00Z',
  },
  {
    id: 'act_6',
    clientId: 'cli_boutique_wellness',
    type: 'project_updated',
    title: 'Project Advanced to Build Stage',
    description: 'Design mockups signed off by Elena. Custom React/Tailwind build underway with booking integrations.',
    timestamp: '2026-10-04T16:00:00Z',
  },
];

export const SAMPLE_EXPENSES: Expense[] = [
  {
    id: 'exp_hl_crm',
    date: '2026-10-01',
    vendor: 'HighLevel CRM & Funnels',
    category: 'Software/Tools',
    amount: 97,
    recurring: 'monthly',
    notes: 'Agency marketing automation, funnels & SMS pipelines',
    receiptLink: 'https://billing.stripe.com',
  },
  {
    id: 'exp_webflow_hosting',
    date: '2026-10-01',
    vendor: 'Webflow Workspace & CMS',
    category: 'Hosting',
    amount: 49,
    recurring: 'monthly',
    notes: 'Core agency staging environment and client templates',
  },
  {
    id: 'exp_vercel_pro',
    date: '2026-10-02',
    vendor: 'Vercel Pro',
    category: 'Hosting',
    amount: 20,
    recurring: 'monthly',
    notes: 'Next.js & React app edge deployments',
  },
  {
    id: 'exp_meta_ads',
    date: '2026-10-03',
    vendor: 'Meta Ads Manager (Self-Promo)',
    category: 'Ads for Dynasty Digital',
    amount: 350,
    recurring: 'monthly',
    notes: 'South Florida local business owner retargeting & lead gen campaign',
  },
  {
    id: 'exp_callrail_palm',
    date: '2026-10-01',
    vendor: 'CallRail Dynamic Tracking',
    category: 'Software/Tools',
    amount: 45,
    recurring: 'monthly',
    clientId: 'cli_palm_shore',
    notes: 'Local pool & landscape call tracking phone numbers for Mateo Alvarez',
  },
  {
    id: 'exp_hosting_goldcoast',
    date: '2026-10-02',
    vendor: 'Cloudflare / DigitalOcean Dedicated VPS',
    category: 'Hosting',
    amount: 35,
    recurring: 'monthly',
    clientId: 'cli_gold_coast',
    notes: 'High-speed image CDN & booking VPS for Gold Coast Auto Detailing',
  },
  {
    id: 'exp_subcontractor_wellness',
    date: '2026-10-04',
    vendor: 'Freelance 3D / Motion Designer (Upwork)',
    category: 'Subcontractor',
    amount: 150,
    recurring: 'one-time',
    clientId: 'cli_boutique_wellness',
    notes: 'Custom hero video motion loop for The Breakers Wellness & Spa launch',
  },
  {
    id: 'exp_insurance',
    date: '2026-06-15',
    vendor: 'Hiscox Small Business Liability',
    category: 'Insurance',
    amount: 600,
    recurring: 'yearly',
    notes: 'Annual E&O + general commercial liability coverage ($50/mo normalized)',
  },
  {
    id: 'exp_adobe_cc',
    date: '2026-10-05',
    vendor: 'Adobe Creative Cloud',
    category: 'Software/Tools',
    amount: 59.99,
    recurring: 'monthly',
    notes: 'Photoshop, Illustrator, Premiere Pro for ad creatives',
  },
];

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: 'inv_dd_0001',
    invoiceNumber: 'DD-2026-0001',
    clientId: 'cli_palm_shore',
    issueDate: '2026-10-01',
    dueDate: '2026-10-15',
    status: 'Paid',
    paidDate: '2026-10-01',
    lineItems: [
      {
        id: 'li_1',
        serviceId: 'srv_palm_care',
        description: 'Website Care Plan: Growth (Monthly Maintenance & Hosting)',
        quantity: 1,
        unitPrice: 297,
        total: 297,
      },
      {
        id: 'li_2',
        serviceId: 'srv_palm_ads',
        description: 'Ads Management: Growth (Google Ads Management & Optimization)',
        quantity: 1,
        unitPrice: 1000,
        total: 1000,
      },
    ],
    subtotal: 1297,
    tax: 0,
    discount: 0,
    total: 1297,
    paymentInstructions: 'ACH Auto-pay configured via Stripe. Remit payments to Dynasty Digital LLC.',
    notes: 'October 2026 monthly retainer. Thank you for your partnership!',
    createdAt: '2026-10-01T08:00:00Z',
    updatedAt: '2026-10-01T10:15:00Z',
  },
  {
    id: 'inv_dd_0002',
    invoiceNumber: 'DD-2026-0002',
    clientId: 'cli_sparkle_pro',
    issueDate: '2026-09-15',
    dueDate: '2026-10-01',
    status: 'Overdue',
    lineItems: [
      {
        id: 'li_3',
        serviceId: 'srv_sparkle_care',
        description: 'Website Care Plan: Essential (Backups, Security & Updates)',
        quantity: 1,
        unitPrice: 97,
        total: 97,
      },
      {
        id: 'li_4',
        serviceId: 'srv_sparkle_ads',
        description: 'Meta Ads Management (Residential Turnover Campaigns)',
        quantity: 1,
        unitPrice: 800,
        total: 800,
      },
    ],
    subtotal: 897,
    tax: 0,
    discount: 0,
    total: 897,
    paymentInstructions: 'Net 15 Terms. Pay online via Stripe card portal or ACH wire.',
    notes: 'Payment is currently past due. Please remit as soon as possible.',
    createdAt: '2026-09-15T08:00:00Z',
    updatedAt: '2026-10-02T09:00:00Z',
  },
  {
    id: 'inv_dd_0003',
    invoiceNumber: 'DD-2026-0003',
    clientId: 'cli_gold_coast',
    issueDate: '2026-10-01',
    dueDate: '2026-10-15',
    status: 'Sent',
    lineItems: [
      {
        id: 'li_5',
        serviceId: 'srv_gc_care',
        description: 'Website Care Plan: Growth (High-Performance VPS & Speed)',
        quantity: 1,
        unitPrice: 297,
        total: 297,
      },
      {
        id: 'li_6',
        serviceId: 'srv_gc_ads',
        description: 'Ads Management: Dominate (Google Search & Local Services Ads)',
        quantity: 1,
        unitPrice: 1800,
        total: 1800,
      },
    ],
    subtotal: 2097,
    tax: 0,
    discount: 0,
    total: 2097,
    paymentInstructions: 'ACH or Corporate Card. Link: https://billing.stripe.com/p/dynasty-goldcoast',
    notes: 'October 2026 retainer. Contract extension review scheduled for Oct 25.',
    createdAt: '2026-10-01T08:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'inv_dd_0004',
    invoiceNumber: 'DD-2026-0004',
    clientId: 'cli_boutique_wellness',
    issueDate: '2026-10-06',
    dueDate: '2026-10-20',
    status: 'Draft',
    lineItems: [
      {
        id: 'li_7',
        serviceId: 'srv_bw_build',
        description: 'Custom Next.js Web Application & JaneApp Booking Engine (50% Milestone)',
        quantity: 1,
        unitPrice: 1600,
        total: 1600,
      },
    ],
    subtotal: 1600,
    tax: 0,
    discount: 0,
    total: 1600,
    paymentInstructions: 'Due on milestone sign-off. Wire instructions provided in client portal.',
    notes: 'Milestone 2 invoice (Design approval complete, proceeding to final build).',
    createdAt: '2026-10-06T14:00:00Z',
    updatedAt: '2026-10-06T14:00:00Z',
  },
];

export const DEFAULT_CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'tmpl_website_build',
    name: 'Website Build',
    serviceCategory: 'Website Build',
    description: '14-step high-converting website build checklist from deposit to review request',
    items: [
      'deposit received',
      'agreement signed',
      'logo/photos/copy received',
      'domain access',
      'mockup approved',
      'build complete',
      'mobile tested',
      'forms tested',
      'Pixel + GA4 installed',
      'favicon',
      'final payment',
      'launched',
      'care plan billing started',
      'Google review requested',
    ],
  },
  {
    id: 'tmpl_ads',
    name: 'Ads',
    serviceCategory: 'Meta Ads',
    description: '8-step paid advertising onboarding and kickoff checklist',
    items: [
      'Business Manager partner access',
      'ad account + payment method',
      'pixel verified',
      'Instant Form built',
      'lead notifications connected',
      'call tracking',
      'kickoff call',
      'ads launched',
    ],
  },
  {
    id: 'tmpl_gbp',
    name: 'GBP',
    serviceCategory: 'Google Business Profile',
    description: '6-step local SEO and Google Business Profile optimization checklist',
    items: [
      'access granted',
      'verified',
      'categories/services',
      '20+ photos',
      'review link/QR sent',
      'citations submitted',
    ],
  },
];

export const SAMPLE_CHECKLISTS: ClientChecklist[] = [
  {
    id: 'chk_palm_shore_web',
    clientId: 'cli_palm_shore',
    serviceId: 'srv_palm_shore_web',
    templateId: 'tmpl_website_build',
    title: 'Website Build: Commercial Redesign',
    createdAt: '2026-09-15T10:00:00Z',
    items: [
      { id: 'item_1', label: 'deposit received', completed: true, completedAt: '2026-09-15T12:00:00Z' },
      { id: 'item_2', label: 'agreement signed', completed: true, completedAt: '2026-09-16T15:30:00Z' },
      { id: 'item_3', label: 'logo/photos/copy received', completed: true, completedAt: '2026-09-18T11:00:00Z' },
      { id: 'item_4', label: 'domain access', completed: true, completedAt: '2026-09-19T09:45:00Z' },
      { id: 'item_5', label: 'mockup approved', completed: true, completedAt: '2026-09-22T16:20:00Z' },
      { id: 'item_6', label: 'build complete', completed: true, completedAt: '2026-09-28T18:00:00Z' },
      { id: 'item_7', label: 'mobile tested', completed: true, completedAt: '2026-09-29T14:15:00Z' },
      { id: 'item_8', label: 'forms tested', completed: true, completedAt: '2026-09-29T16:00:00Z' },
      { id: 'item_9', label: 'Pixel + GA4 installed', completed: true, completedAt: '2026-09-30T10:30:00Z' },
      { id: 'item_10', label: 'favicon', completed: false },
      { id: 'item_11', label: 'final payment', completed: false },
      { id: 'item_12', label: 'launched', completed: false },
      { id: 'item_13', label: 'care plan billing started', completed: false },
      { id: 'item_14', label: 'Google review requested', completed: false },
    ],
  },
  {
    id: 'chk_sparkle_pro_ads',
    clientId: 'cli_sparkle_pro',
    serviceId: 'srv_sparkle_pro_ads',
    templateId: 'tmpl_ads',
    title: 'Ads: Meta Lead Generation Sprint',
    createdAt: '2026-09-28T10:00:00Z',
    items: [
      { id: 'item_1', label: 'Business Manager partner access', completed: true, completedAt: '2026-09-29T11:00:00Z' },
      { id: 'item_2', label: 'ad account + payment method', completed: true, completedAt: '2026-09-29T14:30:00Z' },
      { id: 'item_3', label: 'pixel verified', completed: true, completedAt: '2026-09-30T09:15:00Z' },
      { id: 'item_4', label: 'Instant Form built', completed: true, completedAt: '2026-10-01T16:00:00Z' },
      { id: 'item_5', label: 'lead notifications connected', completed: false },
      { id: 'item_6', label: 'call tracking', completed: false },
      { id: 'item_7', label: 'kickoff call', completed: false },
      { id: 'item_8', label: 'ads launched', completed: false },
    ],
  },
  {
    id: 'chk_gold_coast_gbp',
    clientId: 'cli_gold_coast',
    serviceId: 'srv_gold_coast_gbp',
    templateId: 'tmpl_gbp',
    title: 'GBP: Google Maps & Local Profile Optimization',
    createdAt: '2026-09-20T10:00:00Z',
    items: [
      { id: 'item_1', label: 'access granted', completed: true, completedAt: '2026-09-20T11:00:00Z' },
      { id: 'item_2', label: 'verified', completed: true, completedAt: '2026-09-21T13:00:00Z' },
      { id: 'item_3', label: 'categories/services', completed: true, completedAt: '2026-09-22T10:00:00Z' },
      { id: 'item_4', label: '20+ photos', completed: true, completedAt: '2026-09-25T15:00:00Z' },
      { id: 'item_5', label: 'review link/QR sent', completed: true, completedAt: '2026-09-26T12:00:00Z' },
      { id: 'item_6', label: 'citations submitted', completed: false },
    ],
  },
];

export const SAMPLE_PERFORMANCE_ENTRIES: ClientPerformanceEntry[] = [
  // 1. Palm & Shore Landscaping (cli_palm_shore) - 4 consecutive months of growth
  {
    id: 'perf_ps_2026_07',
    clientId: 'cli_palm_shore',
    month: '2026-07',
    adSpend: 2200,
    leads: 33,
    costPerLead: 66.67,
    bookedJobs: 11,
    revenueFromAds: 13900,
    roas: 6.32,
    gbpCalls: 38,
    gbpDirectionRequests: 16,
    gbpWebsiteClicks: 98,
    whatWeChanged: 'Initial setup of Google Search campaign for "Boca Raton luxury landscaping" and Meta retargeting pixel setup. First batch of geotagged job site photos uploaded to GBP.',
    nextMonthPlan: 'Launch dedicated landing page for high-ticket patio and hardscaping inquiries. Introduce automated SMS lead alert system.',
    notes: 'Mateo confirmed average commercial job size of $1,800+ from paid leads.',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'perf_ps_2026_08',
    clientId: 'cli_palm_shore',
    month: '2026-08',
    adSpend: 2450,
    leads: 38,
    costPerLead: 64.47,
    bookedJobs: 14,
    revenueFromAds: 16800,
    roas: 6.86,
    gbpCalls: 46,
    gbpDirectionRequests: 21,
    gbpWebsiteClicks: 122,
    whatWeChanged: 'Launched High-Ticket Hardscaping ad set targeting homeowners in East Boca & Delray. Added automated instant SMS lead alerts so Mateo calls leads within 5 minutes. Published 8 GBP weekly updates with "Call Now" buttons.',
    nextMonthPlan: 'Test seasonal fall landscape maintenance promos. Increase Meta video retargeting budget by $250. Request 5 new 5-star Google reviews from completed accounts.',
    notes: 'Closing rate improved significantly after implementing fast SMS notifications.',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'perf_ps_2026_09',
    clientId: 'cli_palm_shore',
    month: '2026-09',
    adSpend: 2500,
    leads: 45,
    costPerLead: 55.56,
    bookedJobs: 18,
    revenueFromAds: 21500,
    roas: 8.6,
    gbpCalls: 54,
    gbpDirectionRequests: 27,
    gbpWebsiteClicks: 146,
    whatWeChanged: 'Refined negative keyword list on Google Search Ads to eliminate DIY / free quote searches. Scaled top video hook ad showing completed luxury backyard build. Published geotagged photos to Google Business Profile.',
    nextMonthPlan: 'Scale commercial property manager campaign ahead of Q4. Launch Google Local Services Ads (LSA) alongside current search campaigns. Add QR review signage to crew trucks.',
    notes: 'Record month for client revenue from paid ads.',
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'perf_ps_2026_10',
    clientId: 'cli_palm_shore',
    month: '2026-10',
    adSpend: 2600,
    leads: 51,
    costPerLead: 50.98,
    bookedJobs: 22,
    revenueFromAds: 25800,
    roas: 9.92,
    gbpCalls: 63,
    gbpDirectionRequests: 32,
    gbpWebsiteClicks: 168,
    whatWeChanged: 'Tightened geographic targeting to top-wealth zip codes (33432, 33487, 33483). Optimized Google Business primary category and added 12 new service sub-items. New review acquisition workflow generated 7 new 5-star reviews.',
    nextMonthPlan: 'Holiday & outdoor lighting campaign rollout. Expand Meta retargeting audience to 90-day website visitors. Set up automated missed-call auto-texting for after-hours calls.',
    notes: 'Sub-$51 cost per lead achieved for luxury landscaping in Palm Beach County.',
    createdAt: '2026-10-07T12:00:00Z',
  },

  // 2. Sparkle Pro Cleaning (cli_sparkle_pro)
  {
    id: 'perf_sp_2026_08',
    clientId: 'cli_sparkle_pro',
    month: '2026-08',
    adSpend: 850,
    leads: 32,
    costPerLead: 26.56,
    bookedJobs: 19,
    revenueFromAds: 4750,
    roas: 5.59,
    gbpCalls: 48,
    gbpDirectionRequests: 14,
    gbpWebsiteClicks: 92,
    whatWeChanged: 'Built "First-Time Deep Clean" lead magnet campaign on Meta with instant booking form. Updated Google Business cover photo and created 4 service packages.',
    nextMonthPlan: 'Target Airbnb & vacation rental turnover managers in Fort Lauderdale. Launch before/after photo carousel ads.',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'perf_sp_2026_09',
    clientId: 'cli_sparkle_pro',
    month: '2026-09',
    adSpend: 950,
    leads: 41,
    costPerLead: 23.17,
    bookedJobs: 25,
    revenueFromAds: 6400,
    roas: 6.74,
    gbpCalls: 62,
    gbpDirectionRequests: 18,
    gbpWebsiteClicks: 114,
    whatWeChanged: 'Added instant SMS alerts for Luciana on new lead submissions. Tested 3 short video reels on Instagram Reels ad placements showing move-out cleans.',
    nextMonthPlan: 'Push recurring bi-weekly cleaning package promo. Implement review request links after service completion.',
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'perf_sp_2026_10',
    clientId: 'cli_sparkle_pro',
    month: '2026-10',
    adSpend: 1000,
    leads: 46,
    costPerLead: 21.74,
    bookedJobs: 28,
    revenueFromAds: 7200,
    roas: 7.2,
    gbpCalls: 68,
    gbpDirectionRequests: 22,
    gbpWebsiteClicks: 126,
    whatWeChanged: 'Added automated Google review generation script. Refined Airbnb turnarounds targeting in Fort Lauderdale beach corridor. Optimized GBP hours and local business attributes.',
    nextMonthPlan: 'Prep pre-holiday deep clean promotions for November and December. Test commercial office cleaning ad set.',
    createdAt: '2026-10-07T14:00:00Z',
  },
];

export const SAMPLE_WEBSITES: ClientWebsite[] = [
  // 1. Palm & Shore Landscaping
  {
    id: 'web_palm_shore_main',
    clientId: 'cli_palm_shore',
    domain: 'palmandshorefl.com',
    registrar: 'Cloudflare',
    domainExpiryDate: '2027-04-15',
    registrarLoginOwner: 'us',
    hostingPlatform: 'WP Engine',
    liveUrl: 'https://palmandshorefl.com',
    sslStatus: 'Active',
    lastBackupDate: '2026-10-06',
    lastUpdateDate: '2026-10-05',
    uptimeMonitorLink: 'https://stats.uptimerobot.com/ps-florida-live',
    notes: 'Primary corporate site with local Boca/Delray landing pages. Cloudflare Pro DNS managed by us.',
    createdAt: '2026-02-15T12:00:00Z',
  },

  // 2. Sparkle Pro Cleaning (EXPIRES IN 17 DAYS! Luciana owns login)
  {
    id: 'web_sparkle_pro_main',
    clientId: 'cli_sparkle_pro',
    domain: 'sparkleproclean.com',
    registrar: 'GoDaddy',
    domainExpiryDate: '2026-10-24', // 17 days away! Alert trigger!
    registrarLoginOwner: 'client',
    hostingPlatform: 'Hostinger',
    liveUrl: 'https://sparkleproclean.com',
    sslStatus: 'Active',
    lastBackupDate: '2026-10-06',
    lastUpdateDate: '2026-10-03',
    uptimeMonitorLink: 'https://betteruptime.com/report/sp-clean',
    notes: 'Luciana owns the GoDaddy login with credit card on file. Remind her to confirm auto-renewal.',
    createdAt: '2026-03-01T12:00:00Z',
  },

  // 3. Gold Coast Mobile Detailing (EXPIRES IN 28 DAYS! Dynasty owns login)
  {
    id: 'web_gold_coast_main',
    clientId: 'cli_gold_coast',
    domain: 'goldcoastautodetail.com',
    registrar: 'Namecheap',
    domainExpiryDate: '2026-11-04', // 28 days away! Alert trigger!
    registrarLoginOwner: 'us',
    hostingPlatform: 'Vercel',
    liveUrl: 'https://goldcoastautodetail.com',
    sslStatus: 'Active',
    lastBackupDate: '2026-10-07',
    lastUpdateDate: '2026-10-06',
    uptimeMonitorLink: 'https://stats.uptimerobot.com/gc-autodetail',
    notes: 'Next.js static web app deployed on Vercel with Stripe booking integration. We manage Namecheap account.',
    createdAt: '2026-04-10T12:00:00Z',
  },

  // 4. Apex Roofing & Exteriors
  {
    id: 'web_apex_roof_main',
    clientId: 'cli_apex_roof',
    domain: 'apexroofingfl.com',
    registrar: 'Google Domains / Squarespace',
    domainExpiryDate: '2027-08-19',
    registrarLoginOwner: 'client',
    hostingPlatform: 'WP Engine',
    liveUrl: 'https://apexroofingfl.com',
    sslStatus: 'Active',
    lastBackupDate: '2026-10-06',
    lastUpdateDate: '2026-10-06',
    uptimeMonitorLink: 'https://stats.uptimerobot.com/apex-roof-status',
    notes: 'Client registered domain on Google Domains (now Squarespace Domains). WP Engine managed WordPress.',
    createdAt: '2026-04-20T12:00:00Z',
  },

  // 5. Coastal Glow Wellness (Boutique Wellness)
  {
    id: 'web_boutique_wellness_main',
    clientId: 'cli_boutique_wellness',
    domain: 'coastalglowwellness.com',
    registrar: 'Porkbun',
    domainExpiryDate: '2027-01-12',
    registrarLoginOwner: 'us',
    hostingPlatform: 'DigitalOcean',
    liveUrl: 'https://coastalglowwellness.com',
    sslStatus: 'Active',
    lastBackupDate: '2026-10-06',
    lastUpdateDate: '2026-10-04',
    uptimeMonitorLink: 'https://uptime.dynastysites.net/cg-wellness',
    notes: 'Partner tier care plan. Nightly automated snapshots stored in offsite S3.',
    createdAt: '2026-05-01T12:00:00Z',
  },

  // 6. Pristine Pressure Washing (EXPIRES IN 11 DAYS! Frank owns login)
  {
    id: 'web_pristine_wash_main',
    clientId: 'cli_pristine_wash',
    domain: 'pristinepressurefl.com',
    registrar: 'Namecheap',
    domainExpiryDate: '2026-10-18', // 11 days away! Urgent alert trigger!
    registrarLoginOwner: 'client',
    hostingPlatform: 'SiteGround',
    liveUrl: 'https://pristinepressurefl.com',
    sslStatus: 'Active',
    lastBackupDate: '2026-10-05',
    lastUpdateDate: '2026-10-01',
    uptimeMonitorLink: 'https://stats.uptimerobot.com/pp-wash',
    notes: 'Frank has registrar login. Remind him to renew or transfer domain under Dynasty management.',
    createdAt: '2026-05-15T12:00:00Z',
  },
];

export function getInitialDatabase(): FullDatabase {
  return {
    clients: SAMPLE_CLIENTS,
    catalog: DEFAULT_CATALOG,
    clientServices: SAMPLE_SERVICES,
    payments: SAMPLE_PAYMENTS,
    invoices: SAMPLE_INVOICES,
    projects: SAMPLE_PROJECTS,
    tasks: SAMPLE_TASKS,
    activities: SAMPLE_ACTIVITIES,
    expenses: SAMPLE_EXPENSES,
    checklists: SAMPLE_CHECKLISTS,
    checklistTemplates: DEFAULT_CHECKLIST_TEMPLATES,
    performanceEntries: SAMPLE_PERFORMANCE_ENTRIES,
    websites: SAMPLE_WEBSITES,
    settings: DEFAULT_SETTINGS,
    version: 1,
  };
}
