import React, { useState } from 'react';
import {
  CheckSquare,
  Plus,
  Calendar,
  Check,
  Trash2,
  Filter,
  Sparkles,
  AlertTriangle,
  Clock,
} from 'lucide-react';
import { Client, Task, TaskType, TaskPriority } from '../../types';
import { formatDate } from '../../lib/calculations';
import { StatusBadge } from '../common/StatusBadge';

interface TasksViewProps {
  tasks: Task[];
  clients: Client[];
  onSelectClient: (clientId: string) => void;
  onOpenNewTask: () => void;
  onToggleTask: (taskId: string) => void;
  onDeleteTask: (taskId: string) => void;
}

export function TasksView({
  tasks,
  clients,
  onSelectClient,
  onOpenNewTask,
  onToggleTask,
  onDeleteTask,
}: TasksViewProps) {
  const [selectedType, setSelectedType] = useState<string>('all');
  const [selectedClientId, setSelectedClientId] = useState<string>('all');
  const [showCompleted, setShowCompleted] = useState<boolean>(true);

  const now = new Date();
  const todayStr = now.toISOString().split('T')[0];

  // Filtering
  const filtered = tasks.filter((t) => {
    if (!showCompleted && t.done) return false;
    if (selectedType !== 'all' && t.type !== selectedType) return false;
    if (selectedClientId !== 'all' && t.clientId !== selectedClientId) return false;
    return true;
  });

  // Grouping
  const overdueTasks = filtered.filter((t) => !t.done && t.dueDate < todayStr);
  const todayTasks = filtered.filter((t) => !t.done && t.dueDate === todayStr);
  const upcomingTasks = filtered.filter((t) => !t.done && t.dueDate > todayStr);
  const completedTasks = filtered.filter((t) => t.done);

  const renderTaskCard = (task: Task) => {
    const client = clients.find((c) => c.id === task.clientId);
    const isOverdue = !task.done && task.dueDate < todayStr;

    return (
      <div
        key={task.id}
        className={`p-3.5 rounded-xl border flex items-center justify-between transition-all ${
          task.done
            ? 'bg-[#11131F]/40 border-[#262A40]/40 opacity-60'
            : isOverdue
            ? 'bg-[#11131F] border-[#FF5A5F]/40 shadow-sm shadow-[#FF5A5F]/5'
            : 'bg-[#11131F] border-[#262A40] hover:border-[#22D3EE]/40'
        }`}
      >
        <div className="flex items-center gap-3 min-w-0">
          <button
            onClick={() => onToggleTask(task.id)}
            className={`w-4 h-4 rounded border flex items-center justify-center transition-colors shrink-0 ${
              task.done
                ? 'bg-[#7CFF6B] border-[#7CFF6B] text-[#07080F]'
                : 'border-[#262A40] hover:border-[#7CFF6B]'
            }`}
          >
            {task.done && <Check className="w-3 h-3 stroke-[3]" />}
          </button>

          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span
                className={`text-xs font-medium truncate ${
                  task.done ? 'line-through text-[#A9ADC6]' : 'text-white'
                }`}
              >
                {task.title}
              </span>
              {task.autoGenerated && (
                <span className="font-mono text-[9px] bg-[#22D3EE]/10 border border-[#22D3EE]/20 text-[#22D3EE] px-1.5 py-0.2 rounded shrink-0 flex items-center gap-0.5">
                  <Sparkles className="w-2.5 h-2.5" /> AUTO
                </span>
              )}
            </div>

            <div className="flex items-center gap-2 text-[10px] text-[#A9ADC6] mt-0.5">
              {client && (
                <span
                  onClick={() => onSelectClient(client.id)}
                  className="font-mono text-[#22D3EE] hover:underline cursor-pointer"
                >
                  {client.businessName}
                </span>
              )}
              {client && <span>·</span>}
              <span className={`font-mono ${isOverdue ? 'text-[#FF5A5F] font-bold' : ''}`}>
                Due {formatDate(task.dueDate)}
              </span>
              <span>·</span>
              <StatusBadge status={task.priority} size="sm" />
              <span>·</span>
              <span>{task.type}</span>
            </div>
          </div>
        </div>

        <button
          onClick={() => onDeleteTask(task.id)}
          className="p-1 text-[#A9ADC6] hover:text-[#FF5A5F] shrink-0 ml-2"
          title="Delete Task"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    );
  };

  return (
    <div className="space-y-4">
      {/* Header & Controls */}
      <div className="p-4 rounded-2xl bg-[#11131F] border border-[#262A40] flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div>
          <h2 className="text-base font-semibold text-white">Agency Workflow & Task Board</h2>
          <p className="text-xs text-[#A9ADC6]">
            Automated monthly reports, renewal touchpoints, and custom agency deliverables
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Filter by Type */}
          <select
            value={selectedType}
            onChange={(e) => setSelectedType(e.target.value)}
            className="px-2.5 py-1.5 bg-[#07080F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
          >
            <option value="all">All Task Types</option>
            <option value="Follow-up">Follow-up</option>
            <option value="Build">Build</option>
            <option value="Monthly Care">Monthly Care</option>
            <option value="Report">Report</option>
            <option value="Renewal">Renewal</option>
            <option value="Other">Other</option>
          </select>

          {/* Filter by Client */}
          <select
            value={selectedClientId}
            onChange={(e) => setSelectedClientId(e.target.value)}
            className="px-2.5 py-1.5 bg-[#07080F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white max-w-[180px] truncate"
          >
            <option value="all">All Clients</option>
            {clients.map((c) => (
              <option key={c.id} value={c.id}>
                {c.businessName}
              </option>
            ))}
          </select>

          {/* Toggle Completed */}
          <button
            onClick={() => setShowCompleted((prev) => !prev)}
            className={`px-3 py-1.5 rounded-lg border text-xs font-mono transition-colors ${
              showCompleted
                ? 'bg-[#181B2C] border-[#262A40] text-white'
                : 'bg-[#07080F] border-[#262A40] text-[#A9ADC6]'
            }`}
          >
            {showCompleted ? 'Hide Completed' : 'Show Completed'}
          </button>

          <button
            onClick={onOpenNewTask}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#3D5AFE] hover:bg-[#324bda] text-xs font-medium text-white transition-all shadow-sm"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Add Task</span>
          </button>
        </div>
      </div>

      {/* Task Groups */}
      <div className="space-y-6">
        {/* 1. Overdue */}
        {overdueTasks.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-[#FF5A5F]">
              <AlertTriangle className="w-4 h-4" />
              <span>Overdue Tasks ({overdueTasks.length})</span>
            </div>
            <div className="space-y-2">{overdueTasks.map(renderTaskCard)}</div>
          </div>
        )}

        {/* 2. Today */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-[#22D3EE]">
            <Clock className="w-4 h-4" />
            <span>Due Today ({todayTasks.length})</span>
          </div>
          {todayTasks.length === 0 ? (
            <p className="p-4 rounded-xl bg-[#11131F]/50 border border-[#262A40]/50 text-xs text-[#A9ADC6] italic">
              No tasks due today.
            </p>
          ) : (
            <div className="space-y-2">{todayTasks.map(renderTaskCard)}</div>
          )}
        </div>

        {/* 3. Upcoming */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-white">
            <Calendar className="w-4 h-4 text-[#3D5AFE]" />
            <span>Upcoming Deadlines ({upcomingTasks.length})</span>
          </div>
          {upcomingTasks.length === 0 ? (
            <p className="p-4 rounded-xl bg-[#11131F]/50 border border-[#262A40]/50 text-xs text-[#A9ADC6] italic">
              No upcoming tasks scheduled.
            </p>
          ) : (
            <div className="space-y-2">{upcomingTasks.map(renderTaskCard)}</div>
          )}
        </div>

        {/* 4. Completed */}
        {showCompleted && completedTasks.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono font-semibold text-[#7CFF6B]">
              <Check className="w-4 h-4" />
              <span>Completed ({completedTasks.length})</span>
            </div>
            <div className="space-y-2">{completedTasks.map(renderTaskCard)}</div>
          </div>
        )}
      </div>
    </div>
  );
}
