import React, { useState } from 'react';
import {
  X,
  Copy,
  Check,
  Zap,
  Code,
  ShieldCheck,
  Globe,
  Send,
  Sparkles,
  Layers,
  ArrowRight,
  Eye,
  EyeOff,
  Server,
  FileCode,
} from 'lucide-react';
import { useToast } from '../../context/ToastContext';
import { IncomingLeadPayload } from '../../types';

interface LeadWebhookModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSendTestLead?: (payload: IncomingLeadPayload) => Promise<any>;
}

export function LeadWebhookModal({
  isOpen,
  onClose,
  onSendTestLead,
}: LeadWebhookModalProps) {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<'endpoint' | 'zapier' | 'test' | 'function'>('endpoint');
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [showSecret, setShowSecret] = useState(false);

  // Default secret key
  const secretKey = 'dd_secret_leads_2026_cr';

  // Live URL
  const currentOrigin = typeof window !== 'undefined' ? window.location.origin : '';
  const productionUrl = 'https://ais-pre-yog4du6funb6zzsxbrhmtj-805236908709.us-east1.run.app';
  const endpointPath = '/api/incoming-leads';
  const exactEndpointUrl = currentOrigin
    ? `${currentOrigin}${endpointPath}`
    : `${productionUrl}${endpointPath}`;

  // Test form fields
  const [testName, setTestName] = useState('Marcus Vance');
  const [testEmail, setTestEmail] = useState('marcus@sunshineexteriors.com');
  const [testPhone, setTestPhone] = useState('(954) 890-4122');
  const [testBusiness, setTestBusiness] = useState('Sunshine Exterior Remodeling');
  const [testBusinessType, setTestBusinessType] = useState('Remodeling/Contractor');
  const [testSource, setTestSource] = useState('Meta Lead Ads');
  const [testMessage, setTestMessage] = useState(
    'Interested in a website redesign and local Google Ads lead generation campaign across Broward County.'
  );
  const [isSendingTest, setIsSendingTest] = useState(false);
  const [testResult, setTestResult] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleCopy = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    toast(`Copied ${fieldName} to clipboard`);
    setTimeout(() => {
      setCopiedField(null);
    }, 2000);
  };

  const sampleCurl = `curl -X POST "${exactEndpointUrl}" \\
  -H "Content-Type: application/json" \\
  -H "x-api-key: ${secretKey}" \\
  -d '{
    "name": "Marcus Vance",
    "email": "marcus@sunshineexteriors.com",
    "phone": "(954) 890-4122",
    "business": "Sunshine Exterior Remodeling",
    "businessType": "Remodeling/Contractor",
    "source": "Meta Lead Ads",
    "message": "Interested in a website redesign and local Google Ads lead generation campaign across Broward County."
  }'`;

  const cloudFunctionCode = `// Firebase Cloud Function: incomingLeads
// Save to functions/index.js and run: firebase deploy --only functions
const { onRequest } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore();

const LEADS_SECRET_KEY = process.env.LEADS_SECRET_KEY || '${secretKey}';

exports.incomingLeads = onRequest({ cors: true }, async (req, res) => {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Use POST' });

  const providedKey = req.headers['x-api-key'] || req.body?.secretKey || '';
  if (providedKey !== LEADS_SECRET_KEY) {
    return res.status(401).json({ error: 'Unauthorized: Invalid secret key' });
  }

  const { name, email, phone, business, businessType, source, message } = req.body;
  const now = new Date().toISOString();
  const today = now.split('T')[0];
  const rand = Math.random().toString(36).substring(2, 7);

  const clientId = 'cli_lead_' + Date.now() + '_' + rand;
  const taskId = 'tsk_followup_' + Date.now() + '_' + rand;
  const activityId = 'act_lead_' + Date.now() + '_' + rand;

  const batch = db.batch();
  batch.set(db.collection('clients').doc(clientId), {
    id: clientId,
    businessName: business || name + "'s Business",
    contactName: name || 'Inbound Lead',
    email: email || '',
    phone: phone || '',
    industry: businessType || 'Other',
    leadSource: source || 'Website Form',
    status: 'Lead',
    tags: ['Inbound Lead', source || 'Web'],
    dateAdded: today,
    notes: message ? 'Lead inquiry: ' + message : 'Inbound lead received.',
    leadContacted: false,
    sourceMessage: message || '',
    lastActivityDate: now
  });

  batch.set(db.collection('tasks').doc(taskId), {
    id: taskId,
    clientId: clientId,
    title: '⚡ Follow up within 5 minutes — ' + (name || 'Lead') + ' (' + (business || 'Inbound') + ')',
    dueDate: today,
    priority: 'High',
    done: false,
    type: 'Follow-up',
    autoGenerated: true,
    createdAt: now
  });

  batch.set(db.collection('activities').doc(activityId), {
    id: activityId,
    clientId: clientId,
    type: 'lead_received',
    title: 'Incoming Lead via ' + (source || 'Website Form'),
    description: name + ' submitted lead. Contact: ' + (phone || 'N/A') + ' | ' + (email || 'N/A'),
    timestamp: now
  });

  await batch.commit();
  return res.status(201).json({ success: true, leadId: clientId, taskId: taskId });
});`;

  const handleSendTest = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSendingTest(true);
    setTestResult(null);

    const payload: IncomingLeadPayload = {
      name: testName,
      email: testEmail,
      phone: testPhone,
      business: testBusiness,
      businessType: testBusinessType,
      source: testSource,
      message: testMessage,
      secretKey: secretKey,
    };

    try {
      if (onSendTestLead) {
        await onSendTestLead(payload);
        setTestResult(`Success! Created lead "${testBusiness}" with urgent 5-minute follow-up task.`);
        toast('Test lead created successfully!');
      } else {
        // Direct fetch to endpoint
        const res = await fetch('/api/incoming-leads', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': secretKey,
          },
          body: JSON.stringify(payload),
        });
        const data = await res.json();
        if (res.ok) {
          setTestResult(`Success! Created lead "${testBusiness}" (ID: ${data?.lead?.id || 'OK'}).`);
          toast('Test lead posted to endpoint successfully!');
        } else {
          setTestResult(`Error: ${data?.message || 'Failed to send'}`);
        }
      }
    } catch (err: any) {
      setTestResult(`Error: ${err?.message || 'Network request failed'}`);
    } finally {
      setIsSendingTest(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md overflow-y-auto">
      <div className="w-full max-w-3xl my-8 rounded-2xl bg-[#11131F] border border-[#262A40] shadow-2xl flex flex-col max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="p-5 border-b border-[#262A40] flex items-center justify-between shrink-0 bg-[#07080F]/50">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-[#22D3EE]/15 text-[#22D3EE] border border-[#22D3EE]/30">
              <Zap className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-white">Incoming Leads Webhook & Zapier API</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-[#7CFF6B]/15 text-[#7CFF6B] border border-[#7CFF6B]/30">
                  Live & Active
                </span>
              </div>
              <p className="text-xs text-[#A9ADC6] mt-0.5">
                Automatically ingest leads from Website forms & Meta Lead Ads, create CRM records, and trigger 5-minute follow-up tasks
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-[#A9ADC6] hover:text-white hover:bg-[#181B2C] transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Buttons */}
        <div className="flex items-center gap-1 px-5 pt-3 border-b border-[#262A40] bg-[#07080F]/30 overflow-x-auto shrink-0">
          {[
            { id: 'endpoint', label: 'Endpoint & curl', icon: Server },
            { id: 'zapier', label: 'Zapier & Meta Setup', icon: Layers },
            { id: 'test', label: 'Test Inbound Lead', icon: Send },
            { id: 'function', label: 'Firebase Cloud Function Code', icon: FileCode },
          ].map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-2 px-3.5 py-2.5 text-xs font-medium border-b-2 transition-all cursor-pointer whitespace-nowrap ${
                  isActive
                    ? 'border-[#22D3EE] text-[#22D3EE] bg-[#11131F]/50'
                    : 'border-transparent text-[#A9ADC6] hover:text-white'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Content Body */}
        <div className="p-5 overflow-y-auto space-y-5 flex-1">
          {/* TAB 1: ENDPOINT & CURL */}
          {activeTab === 'endpoint' && (
            <div className="space-y-4">
              {/* Endpoint URL Card */}
              <div className="p-4 rounded-xl bg-[#07080F] border border-[#262A40] space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-[#A9ADC6] flex items-center gap-1.5">
                    <Globe className="w-3.5 h-3.5 text-[#22D3EE]" />
                    <span>Exact Webhook Endpoint URL (POST)</span>
                  </span>
                  <span className="text-[10px] font-mono text-[#7CFF6B] bg-[#7CFF6B]/10 px-2 py-0.5 rounded border border-[#7CFF6B]/20">
                    HTTP 201 Created
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <input
                    type="text"
                    readOnly
                    value={exactEndpointUrl}
                    className="flex-1 px-3 py-2 bg-[#11131F] border border-[#262A40] rounded-lg text-xs font-mono text-[#22D3EE] focus:outline-none select-all"
                  />
                  <button
                    onClick={() => handleCopy(exactEndpointUrl, 'Endpoint URL')}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-[#3D5AFE] hover:bg-[#324CDD] text-white text-xs font-medium transition-colors cursor-pointer shrink-0 shadow-sm"
                  >
                    {copiedField === 'Endpoint URL' ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-[#7CFF6B]" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy URL</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Secret Key Card */}
              <div className="p-4 rounded-xl bg-[#07080F] border border-[#262A40] space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-[#A9ADC6] flex items-center gap-1.5">
                    <ShieldCheck className="w-3.5 h-3.5 text-[#F5A524]" />
                    <span>Webhook Secret Key (Authentication)</span>
                  </span>
                  <button
                    onClick={() => setShowSecret(!showSecret)}
                    className="text-[11px] font-mono text-[#22D3EE] hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    {showSecret ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
                    <span>{showSecret ? 'Hide' : 'Reveal'}</span>
                  </button>
                </div>
                <div className="flex items-center gap-2">
                  <input
                    type={showSecret ? 'text' : 'password'}
                    readOnly
                    value={secretKey}
                    className="flex-1 px-3 py-2 bg-[#11131F] border border-[#262A40] rounded-lg text-xs font-mono text-white focus:outline-none select-all"
                  />
                  <button
                    onClick={() => handleCopy(secretKey, 'Secret Key')}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-[#181B2C] hover:bg-[#262A40] border border-[#262A40] text-white text-xs font-medium transition-colors cursor-pointer shrink-0"
                  >
                    {copiedField === 'Secret Key' ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-[#7CFF6B]" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy Secret</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-[11px] text-[#A9ADC6] mt-1">
                  Pass this key via the <code className="text-[#22D3EE] font-mono">x-api-key</code> HTTP header or in the JSON payload body as <code className="text-[#22D3EE] font-mono">secretKey</code>.
                </p>
              </div>

              {/* Sample curl command */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-white flex items-center gap-1.5">
                    <Code className="w-3.5 h-3.5 text-[#22D3EE]" />
                    <span>Ready-to-Run Sample curl Command</span>
                  </span>
                  <button
                    onClick={() => handleCopy(sampleCurl, 'curl command')}
                    className="flex items-center gap-1 text-[11px] font-mono text-[#22D3EE] hover:underline cursor-pointer"
                  >
                    {copiedField === 'curl command' ? (
                      <>
                        <Check className="w-3 h-3 text-[#7CFF6B]" />
                        <span className="text-[#7CFF6B]">Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy curl</span>
                      </>
                    )}
                  </button>
                </div>
                <div className="relative p-3.5 rounded-xl bg-[#07080F] border border-[#262A40] font-mono text-xs text-[#22D3EE] overflow-x-auto leading-relaxed">
                  <pre className="text-white whitespace-pre-wrap">{sampleCurl}</pre>
                </div>
              </div>

              {/* Automated Actions Explained */}
              <div className="p-4 rounded-xl bg-[#11131F] border border-[#262A40] space-y-2.5">
                <h4 className="text-xs font-bold text-white uppercase tracking-wider">
                  Automated Actions Triggered on Ingestion:
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-[#A9ADC6]">
                  <div className="flex items-start gap-2 p-2 rounded-lg bg-[#07080F] border border-[#262A40]">
                    <span className="w-5 h-5 rounded-md bg-[#22D3EE]/20 text-[#22D3EE] flex items-center justify-center font-bold text-[10px] shrink-0">1</span>
                    <span>Creates CRM Client with status <strong>"Lead"</strong> & source tags</span>
                  </div>
                  <div className="flex items-start gap-2 p-2 rounded-lg bg-[#07080F] border border-[#262A40]">
                    <span className="w-5 h-5 rounded-md bg-[#FF5A5F]/20 text-[#FF5A5F] flex items-center justify-center font-bold text-[10px] shrink-0">2</span>
                    <span>Schedules High-Priority <strong>"⚡ Follow up within 5 minutes"</strong> Task</span>
                  </div>
                  <div className="flex items-start gap-2 p-2 rounded-lg bg-[#07080F] border border-[#262A40]">
                    <span className="w-5 h-5 rounded-md bg-[#7CFF6B]/20 text-[#7CFF6B] flex items-center justify-center font-bold text-[10px] shrink-0">3</span>
                    <span>Displays prominent <strong>"⚡ Uncontacted Lead"</strong> alert badges</span>
                  </div>
                  <div className="flex items-start gap-2 p-2 rounded-lg bg-[#07080F] border border-[#262A40]">
                    <span className="w-5 h-5 rounded-md bg-[#F5A524]/20 text-[#F5A524] flex items-center justify-center font-bold text-[10px] shrink-0">4</span>
                    <span>Records timestamped activity log with full contact details & notes</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: ZAPIER & META SETUP */}
          {activeTab === 'zapier' && (
            <div className="space-y-4 text-xs">
              <div className="p-4 rounded-xl bg-[#07080F] border border-[#262A40] space-y-3">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Layers className="w-4 h-4 text-[#F5A524]" />
                  <span>Connecting Meta Lead Ads via Zapier (3-Minute Setup)</span>
                </h3>
                <p className="text-[#A9ADC6] leading-relaxed">
                  Zapier connects Meta (Facebook & Instagram) Lead Ads or your website forms (Elementor, Webflow, Squarespace, Gravity Forms) straight into Dynasty Digital CRM.
                </p>

                <div className="space-y-3 pt-2">
                  <div className="p-3 rounded-lg bg-[#11131F] border border-[#262A40] space-y-1">
                    <div className="font-semibold text-white">Step 1: Choose Trigger App</div>
                    <div className="text-[#A9ADC6]">
                      Select <strong>"Facebook Lead Ads"</strong> (Event: "New Lead") or your website form provider (Elementor Forms / Webflow / Typeform).
                    </div>
                  </div>

                  <div className="p-3 rounded-lg bg-[#11131F] border border-[#262A40] space-y-1">
                    <div className="font-semibold text-white">Step 2: Choose Action App</div>
                    <div className="text-[#A9ADC6]">
                      Select <strong>"Webhooks by Zapier"</strong> &rarr; Choose <strong>"Custom Request"</strong> or <strong>"POST"</strong>.
                    </div>
                  </div>

                  <div className="p-3 rounded-lg bg-[#11131F] border border-[#262A40] space-y-2">
                    <div className="font-semibold text-white">Step 3: Configure Webhook Parameters</div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] font-mono">
                      <div className="p-2 rounded bg-[#07080F] border border-[#262A40]">
                        <span className="text-[#A9ADC6] block">URL:</span>
                        <span className="text-[#22D3EE] break-all">{exactEndpointUrl}</span>
                      </div>
                      <div className="p-2 rounded bg-[#07080F] border border-[#262A40]">
                        <span className="text-[#A9ADC6] block">Payload Type:</span>
                        <span className="text-white">json</span>
                      </div>
                    </div>
                  </div>

                  <div className="p-3 rounded-lg bg-[#11131F] border border-[#262A40] space-y-2">
                    <div className="font-semibold text-white">Step 4: Map Meta Lead Form Fields to JSON Data</div>
                    <div className="overflow-x-auto">
                      <table className="w-full text-left font-mono text-[11px]">
                        <thead>
                          <tr className="text-[#A9ADC6] border-b border-[#262A40]">
                            <th className="pb-1.5">JSON Key</th>
                            <th className="pb-1.5">Meta / Form Field Value</th>
                            <th className="pb-1.5">Description</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-[#262A40]/50 text-white">
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">name</td>
                            <td className="py-1.5 text-[#F5A524]">Full Name (or First + Last)</td>
                            <td className="py-1.5 text-[#A9ADC6]">Contact person name</td>
                          </tr>
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">email</td>
                            <td className="py-1.5 text-[#F5A524]">Email Address</td>
                            <td className="py-1.5 text-[#A9ADC6]">Direct email address</td>
                          </tr>
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">phone</td>
                            <td className="py-1.5 text-[#F5A524]">Phone Number</td>
                            <td className="py-1.5 text-[#A9ADC6]">Direct phone number</td>
                          </tr>
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">business</td>
                            <td className="py-1.5 text-[#F5A524]">Company Name</td>
                            <td className="py-1.5 text-[#A9ADC6]">Business / organization name</td>
                          </tr>
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">businessType</td>
                            <td className="py-1.5 text-[#F5A524]">Industry / Service Requested</td>
                            <td className="py-1.5 text-[#A9ADC6]">e.g. "Remodeling", "Cleaning"</td>
                          </tr>
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">source</td>
                            <td className="py-1.5 text-[#F5A524]">"Meta Lead Ads"</td>
                            <td className="py-1.5 text-[#A9ADC6]">Marketing channel identifier</td>
                          </tr>
                          <tr>
                            <td className="py-1.5 text-[#22D3EE]">message</td>
                            <td className="py-1.5 text-[#F5A524]">Questions / Custom Answers</td>
                            <td className="py-1.5 text-[#A9ADC6]">Lead inquiry notes</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>

                  <div className="p-3 rounded-lg bg-[#11131F] border border-[#262A40] space-y-1">
                    <div className="font-semibold text-white">Step 5: Set HTTP Headers</div>
                    <div className="p-2 rounded bg-[#07080F] border border-[#262A40] font-mono text-[11px] text-[#22D3EE]">
                      x-api-key: {secretKey}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: TEST INBOUND LEAD */}
          {activeTab === 'test' && (
            <form onSubmit={handleSendTest} className="space-y-4">
              <div className="p-4 rounded-xl bg-[#07080F] border border-[#262A40] space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-bold text-white flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-[#7CFF6B]" />
                      <span>Simulate Inbound Lead</span>
                    </h3>
                    <p className="text-xs text-[#A9ADC6] mt-0.5">
                      Send a test lead now to verify CRM ingestion, the uncontacted badge, and the 5-minute task.
                    </p>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
                  <div>
                    <label className="text-[11px] text-[#A9ADC6] block mb-1">Contact Name</label>
                    <input
                      type="text"
                      value={testName}
                      onChange={(e) => setTestName(e.target.value)}
                      required
                      className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                    />
                  </div>

                  <div>
                    <label className="text-[11px] text-[#A9ADC6] block mb-1">Business Name</label>
                    <input
                      type="text"
                      value={testBusiness}
                      onChange={(e) => setTestBusiness(e.target.value)}
                      required
                      className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                    />
                  </div>

                  <div>
                    <label className="text-[11px] text-[#A9ADC6] block mb-1">Email Address</label>
                    <input
                      type="email"
                      value={testEmail}
                      onChange={(e) => setTestEmail(e.target.value)}
                      required
                      className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                    />
                  </div>

                  <div>
                    <label className="text-[11px] text-[#A9ADC6] block mb-1">Phone Number</label>
                    <input
                      type="text"
                      value={testPhone}
                      onChange={(e) => setTestPhone(e.target.value)}
                      required
                      className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                    />
                  </div>

                  <div>
                    <label className="text-[11px] text-[#A9ADC6] block mb-1">Business Type / Niche</label>
                    <input
                      type="text"
                      value={testBusinessType}
                      onChange={(e) => setTestBusinessType(e.target.value)}
                      className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                    />
                  </div>

                  <div>
                    <label className="text-[11px] text-[#A9ADC6] block mb-1">Lead Source</label>
                    <select
                      value={testSource}
                      onChange={(e) => setTestSource(e.target.value)}
                      className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                    >
                      <option value="Meta Lead Ads">Meta Lead Ads</option>
                      <option value="Website Form">Website Form</option>
                      <option value="Google Ads">Google Ads</option>
                      <option value="Instagram">Instagram</option>
                      <option value="Zapier Webhook">Zapier Webhook</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="text-[11px] text-[#A9ADC6] block mb-1">Inquiry / Message</label>
                  <textarea
                    rows={2}
                    value={testMessage}
                    onChange={(e) => setTestMessage(e.target.value)}
                    className="w-full px-3 py-2 bg-[#11131F] border border-[#262A40] focus:border-[#22D3EE] rounded-lg text-xs text-white"
                  />
                </div>

                {testResult && (
                  <div
                    className={`p-3 rounded-lg text-xs font-mono ${
                      testResult.startsWith('Success')
                        ? 'bg-[#7CFF6B]/15 text-[#7CFF6B] border border-[#7CFF6B]/30'
                        : 'bg-[#FF5A5F]/15 text-[#FF5A5F] border border-[#FF5A5F]/30'
                    }`}
                  >
                    {testResult}
                  </div>
                )}

                <div className="pt-2 flex items-center justify-end">
                  <button
                    type="submit"
                    disabled={isSendingTest}
                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#3D5AFE] hover:bg-[#324CDD] disabled:opacity-50 text-white text-xs font-semibold shadow-md transition-all cursor-pointer"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>{isSendingTest ? 'Sending Test Lead...' : 'Send Test Lead Now'}</span>
                  </button>
                </div>
              </div>
            </form>
          )}

          {/* TAB 4: FIREBASE CLOUD FUNCTION CODE */}
          {activeTab === 'function' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-sm font-bold text-white flex items-center gap-2">
                    <FileCode className="w-4 h-4 text-[#22D3EE]" />
                    <span>Standalone Firebase Cloud Function (v2 HTTPS)</span>
                  </h3>
                  <p className="text-xs text-[#A9ADC6] mt-0.5">
                    Included in your repo at <code className="text-[#22D3EE]">functions/index.js</code>. Deploy with Firebase CLI if desired.
                  </p>
                </div>
                <button
                  onClick={() => handleCopy(cloudFunctionCode, 'Cloud Function Code')}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#181B2C] hover:bg-[#262A40] text-xs font-mono text-[#22D3EE] border border-[#262A40] transition-colors cursor-pointer"
                >
                  {copiedField === 'Cloud Function Code' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-[#7CFF6B]" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Function</span>
                    </>
                  )}
                </button>
              </div>

              <div className="p-3.5 rounded-xl bg-[#07080F] border border-[#262A40] font-mono text-xs text-white overflow-x-auto max-h-[350px]">
                <pre className="whitespace-pre-wrap text-[#A9ADC6]">{cloudFunctionCode}</pre>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-[#262A40] bg-[#07080F]/50 flex items-center justify-between shrink-0">
          <div className="text-[11px] text-[#A9ADC6] font-mono">
            Secret Key: <span className="text-[#22D3EE]">{secretKey}</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-[#181B2C] hover:bg-[#262A40] text-xs font-medium text-white transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
