export type Industry =
  | 'Cleaning'
  | 'Landscaping'
  | 'Auto Detailing'
  | 'Remodeling/Contractor'
  | 'Pressure Washing'
  | 'HVAC'
  | 'Wellness'
  | 'Restaurant'
  | 'Retail'
  | 'Other';

export type LeadSource =
  | 'Meta Ads'
  | 'Google Ads'
  | 'Referral'
  | 'Cold Outreach'
  | 'Website Form'
  | 'Google Business'
  | 'Other';

export type ClientStatus =
  | 'Lead'
  | 'Proposal Sent'
  | 'Active Client'
  | 'Paused'
  | 'Past Client'
  | 'Lost';

export type ESignStatus = 'Draft' | 'Sent for Signature' | 'Signed' | 'Declined' | 'Not Sent';

export interface ProposalDoc {
  link?: string;
  sentDate?: string; // YYYY-MM-DD
  acceptedDate?: string; // YYYY-MM-DD
}

export interface AgreementDoc {
  link?: string;
  signedDate?: string; // YYYY-MM-DD
  eSignStatus: ESignStatus;
}

export interface ClientFileLink {
  id: string;
  title: string;
  url: string;
  category?: string; // "Brand Assets", "Access & Logins", "Creative", "Legal", "Other"
  addedDate?: string; // YYYY-MM-DD
}

export interface ClientDocuments {
  proposal?: ProposalDoc;
  agreement?: AgreementDoc;
  paymentTermsVersion?: string; // e.g. "DD-Standard Net 15 v2026.1"
  paymentTermsSummary?: string;
  fileLinks?: ClientFileLink[];
}

export interface Client {
  id: string;
  businessName: string;
  contactName: string;
  email: string;
  phone: string;
  website: string;
  address: string;
  city: string;
  industry: Industry;
  leadSource: LeadSource;
  status: ClientStatus;
  tags: string[];
  dateAdded: string; // YYYY-MM-DD
  notes: string;
  accessInfo: string; // "Where access lives"
  archived?: boolean;
  lastActivityDate?: string;
  documents?: ClientDocuments;
  leadContacted?: boolean; // false for new uncontacted leads
  contactedAt?: string;
  sourceMessage?: string; // original inquiry message submitted
}

export type BillingType = 'one-time' | 'monthly';

export interface ServiceCatalogItem {
  id: string;
  name: string;
  category: string; // e.g. "Website Build", "Website Care Plan", "Google Business Profile", "Ads Management", "Creative Add-on"
  billingType: BillingType;
  defaultPrice: number;
  setupFee: number;
  minimumTermMonths: number;
  active: boolean;
}

export type ServiceStatus = 'Pending' | 'Active' | 'Paused' | 'Cancelled' | 'Completed';

export interface ClientService {
  id: string;
  clientId: string;
  catalogItemId?: string;
  customName: string;
  category?: string;
  billingType: BillingType;
  price: number;
  setupFee: number;
  discountType: 'percent' | 'fixed';
  discountValue: number;
  startDate: string; // YYYY-MM-DD
  minimumTermMonths: number;
  endDate: string; // YYYY-MM-DD
  autoRenew: boolean;
  status: ServiceStatus;
  billingDayOfMonth: number; // 1-31
  adSpendBudget?: number;
  notes?: string;
}

export type PaymentMethod = 'ACH' | 'Card/Stripe' | 'Cash' | 'Zelle' | 'Other';
export type PaymentType = 'Deposit' | 'Final' | 'Monthly' | 'Setup' | 'Add-on';
export type PaymentStatus = 'Paid' | 'Pending' | 'Failed' | 'Refunded';

export interface Payment {
  id: string;
  clientId: string;
  clientServiceId?: string;
  amount: number;
  date: string; // YYYY-MM-DD
  method: PaymentMethod;
  type: PaymentType;
  status: PaymentStatus;
  invoiceNumber: string;
  notes?: string;
}

export type ProjectStage =
  | 'Mockup'
  | 'Proposal'
  | 'Deposit Paid'
  | 'Design'
  | 'Build'
  | 'Review'
  | 'Final Payment'
  | 'Launched';

export interface Project {
  id: string;
  clientId: string;
  name: string;
  stage: ProjectStage;
  mockupDue?: string; // YYYY-MM-DD
  targetLaunch?: string; // YYYY-MM-DD
  depositPaid: boolean;
  finalPaid: boolean;
  previewLink?: string;
  liveLink?: string;
  notes?: string;
  updatedAt?: string;
}

export type TaskPriority = 'Low' | 'Medium' | 'High';
export type TaskType = 'Follow-up' | 'Build' | 'Monthly Care' | 'Report' | 'Renewal' | 'Other';

export interface Task {
  id: string;
  clientId?: string;
  title: string;
  dueDate: string; // YYYY-MM-DD
  priority: TaskPriority;
  done: boolean;
  type: TaskType;
  createdAt: string;
  autoGenerated?: boolean;
}

export type ActivityType =
  | 'status_change'
  | 'service_added'
  | 'service_updated'
  | 'payment_logged'
  | 'project_updated'
  | 'task_created'
  | 'note'
  | 'call'
  | 'text'
  | 'email'
  | 'meeting'
  | 'lead_received';

export interface ActivityLog {
  id: string;
  clientId: string;
  type: ActivityType;
  title: string;
  description: string;
  timestamp: string; // ISO
}

export interface AppSettings {
  agencyName: string;
  phone: string;
  email: string;
  website: string;
  location: string;
  defaultBillingDay: number;
  pinEnabled: boolean;
  pinCode: string;
  leadsSecretKey?: string;
}

export interface IncomingLeadPayload {
  name?: string;
  contactName?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  business?: string;
  businessName?: string;
  businessType?: string;
  business_type?: string;
  industry?: string;
  source?: string;
  leadSource?: string;
  message?: string;
  notes?: string;
  secretKey?: string;
  apiKey?: string;
}

export type ExpenseCategory =
  | 'Software/Tools'
  | 'Hosting'
  | 'Subcontractor'
  | 'Ads for Dynasty Digital'
  | 'Equipment'
  | 'Insurance'
  | 'Fees'
  | 'Other';

export type ExpenseRecurring = 'monthly' | 'yearly' | 'one-time';

export interface Expense {
  id: string;
  date: string; // YYYY-MM-DD
  vendor: string;
  category: ExpenseCategory;
  amount: number;
  recurring: ExpenseRecurring;
  clientId?: string;
  notes?: string;
  receiptLink?: string;
}

export type InvoiceStatus = 'Draft' | 'Sent' | 'Paid' | 'Overdue';

export interface InvoiceLineItem {
  id: string;
  serviceId?: string;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface Invoice {
  id: string;
  invoiceNumber: string; // e.g. "DD-2026-0001"
  clientId: string;
  issueDate: string; // YYYY-MM-DD
  dueDate: string; // YYYY-MM-DD
  status: InvoiceStatus;
  lineItems: InvoiceLineItem[];
  subtotal: number;
  tax?: number;
  discount?: number;
  total: number;
  paymentInstructions?: string;
  notes?: string;
  createdAt: string;
  updatedAt?: string;
  paidDate?: string;
}

export interface ChecklistTemplate {
  id: string;
  name: string;
  serviceCategory?: string;
  description?: string;
  items: string[];
}

export interface ClientChecklistItem {
  id: string;
  label: string;
  completed: boolean;
  completedAt?: string;
}

export interface ClientChecklist {
  id: string;
  clientId: string;
  serviceId?: string;
  templateId?: string;
  title: string;
  items: ClientChecklistItem[];
  createdAt: string;
  updatedAt?: string;
}

export interface ClientPerformanceEntry {
  id: string;
  clientId: string;
  month: string; // YYYY-MM e.g. "2026-10"
  // Paid Ads metrics
  adSpend: number; // ad spend in dollars
  leads: number; // number of leads generated
  costPerLead: number; // auto-calculated: adSpend / leads
  bookedJobs: number; // client-reported booked jobs count
  revenueFromAds: number; // revenue in dollars
  roas: number; // auto-calculated: revenueFromAds / adSpend
  // Google Business Profile metrics
  gbpCalls: number; // calls generated
  gbpDirectionRequests: number; // direction requests
  gbpWebsiteClicks: number; // website clicks from GBP
  // Narrative strategy & review fields
  whatWeChanged: string; // what we changed this month / optimizations
  nextMonthPlan: string; // next month's plan / strategic initiatives
  notes?: string;
  createdAt: string;
  updatedAt?: string;
}

export type RegistrarLoginOwner = 'client' | 'us';
export type SSLStatus = 'Active' | 'Expiring Soon' | 'Expired' | 'Pending' | 'Unknown';

export interface ClientWebsite {
  id: string;
  clientId: string;
  domain: string; // e.g. "palmandshorefl.com"
  registrar: string; // e.g. "Cloudflare", "GoDaddy", "Namecheap", "Porkbun", "Google Domains / Squarespace"
  domainExpiryDate: string; // YYYY-MM-DD
  registrarLoginOwner: RegistrarLoginOwner; // 'client' | 'us'
  hostingPlatform: string; // e.g. "WP Engine", "Hostinger", "Vercel", "DigitalOcean", "SiteGround"
  liveUrl: string; // e.g. "https://palmandshorefl.com"
  sslStatus: SSLStatus; // 'Active' | 'Expiring Soon' | 'Expired' | 'Pending' | 'Unknown'
  lastBackupDate?: string; // YYYY-MM-DD
  lastUpdateDate?: string; // YYYY-MM-DD
  uptimeMonitorLink?: string; // URL e.g. "https://stats.uptimerobot.com/..."
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface FullDatabase {
  clients: Client[];
  catalog: ServiceCatalogItem[];
  clientServices: ClientService[];
  payments: Payment[];
  invoices: Invoice[];
  projects: Project[];
  tasks: Task[];
  activities: ActivityLog[];
  expenses: Expense[];
  checklists: ClientChecklist[];
  checklistTemplates: ChecklistTemplate[];
  performanceEntries: ClientPerformanceEntry[];
  websites: ClientWebsite[];
  settings: AppSettings;
  version: number;
}
